import praw

# fill in the below 5 None values
# See readme for instructions
# values must be in quotes
# eg: username = 'ItoXICI'

client_secret = None
client_id = None
username = None
password = None
user_agent = None

roundfile = "rounds/rounds.yaml"
archivefile = "rounds/archive.yaml"

debug = False

reddit = praw.Reddit(
    client_id=client_id,
    client_secret=client_secret,
    user_agent=user_agent,
    username=username,
    password=password,
)

pg = reddit.subreddit('itoxtestingfacility' if debug else 'picturegame')


donotreply = {
    'achievements-bot',
    username.lower(),
    'r-picturegame',
    'imreallycuriousbird',
}

incorrect = '❌'

coords_not_found = """
If this is a guess, I was not able to find your coordinates. 
If you did indeed guess coordinates which I did not understand, 
my human friend will come check those for you (but they are much slower than me so be patient)

This message was generated by a botterino, if you experience any issues please contact /u/getoofded
"""