[metadata]
name = botterino
version = 0.6.1
author = itoxici
author_email = itox@picturegame.co
description = Automate posting and hosting of rounds on /r/picturegame
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/pgitox/botterino
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
include_package_data = True
install_requires=
    folium
    praw>=7
    geopy>=2
    pyyaml
    ruamel.yaml
    sty
    requests
    update_checker
    halo
    colorama>=0.4.6

[options.entry_points]
console_scripts =
    botterino = botterino.__main__:run
    botterino-ui = botterino.ui:main
    botterino-check = botterino.validate:main
    botterino-setup = botterino.configure:main
    botterino-failure = botterino.failure:main
